version: "3.9"
services:
  flask:
    build: { context: ../../services/flask-api, dockerfile: Dockerfile.flask }
    ports: ["5000:5000"]
  render:
    build: { context: ../../services/golang-render, dockerfile: Dockerfile.golang }
    ports: ["8080:8080"]
  frontend:
    build: { context: ../../services/js-frontend, dockerfile: Dockerfile.js }
    ports: ["3000:3000"]
  gateway:
    image: nginx:latest
    volumes:
      - ../../gateway/nginx.conf:/etc/nginx/nginx.conf
    ports: ["80:80"]
